-- ==========================================================================
-- Pokemon LocalDex Battle Effects Seed Data (Idempotent)
-- Generated by scripts/gen-seed-sql.py
-- Enum reference: packages/store/shared-types/src/battle-effects.ts
-- ==========================================================================

-- Drop and recreate tables (faster than DELETE for full reseed)
DROP TABLE IF EXISTS move_battle_effects;
DROP TABLE IF EXISTS item_battle_effects;
DROP TABLE IF EXISTS ability_battle_effects;
DROP TABLE IF EXISTS move_flags;

CREATE TABLE IF NOT EXISTS move_flags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  move_id INTEGER NOT NULL REFERENCES moves(id) ON DELETE CASCADE,
  flag INTEGER NOT NULL,
  UNIQUE (move_id, flag)
);

CREATE TABLE IF NOT EXISTS ability_battle_effects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ability_id INTEGER NOT NULL REFERENCES abilities(id) ON DELETE CASCADE,
  effect_type INTEGER NOT NULL,
  trigger INTEGER NOT NULL DEFAULT 1,
  target INTEGER NOT NULL DEFAULT 1,
  modifier_type INTEGER NOT NULL,
  modifier_value REAL,
  affected_stat INTEGER,
  affected_type INTEGER,
  affected_move_flag INTEGER,
  affected_move_category INTEGER,
  params TEXT,
  generation_start INTEGER NOT NULL DEFAULT 1,
  generation_end INTEGER,
  priority INTEGER NOT NULL DEFAULT 0,
  note TEXT
);

CREATE TABLE IF NOT EXISTS item_battle_effects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  effect_type INTEGER NOT NULL,
  trigger INTEGER NOT NULL DEFAULT 1,
  target INTEGER NOT NULL DEFAULT 1,
  modifier_type INTEGER NOT NULL,
  modifier_value REAL,
  affected_stat INTEGER,
  affected_type INTEGER,
  affected_move_flag INTEGER,
  affected_move_category INTEGER,
  params TEXT,
  consumable INTEGER NOT NULL DEFAULT 0,
  species_restriction TEXT,
  generation_start INTEGER NOT NULL DEFAULT 1,
  generation_end INTEGER,
  priority INTEGER NOT NULL DEFAULT 0,
  note TEXT
);

CREATE TABLE IF NOT EXISTS move_battle_effects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  move_id INTEGER NOT NULL REFERENCES moves(id) ON DELETE CASCADE,
  effect_type INTEGER NOT NULL,
  trigger INTEGER NOT NULL DEFAULT 7,
  target INTEGER NOT NULL DEFAULT 2,
  modifier_type INTEGER NOT NULL,
  modifier_value REAL,
  affected_stat INTEGER,
  affected_type INTEGER,
  affected_move_flag INTEGER,
  affected_move_category INTEGER,
  params TEXT,
  generation_start INTEGER NOT NULL DEFAULT 1,
  generation_end INTEGER,
  priority INTEGER NOT NULL DEFAULT 0,
  note TEXT
);

-- Recreate indexes
CREATE INDEX IF NOT EXISTS idx_move_flags_move ON move_flags(move_id);
CREATE INDEX IF NOT EXISTS idx_move_flags_flag ON move_flags(flag);
CREATE INDEX IF NOT EXISTS idx_abe_ability ON ability_battle_effects(ability_id);
CREATE INDEX IF NOT EXISTS idx_abe_effect_type ON ability_battle_effects(effect_type);
CREATE INDEX IF NOT EXISTS idx_abe_trigger ON ability_battle_effects(trigger);
CREATE INDEX IF NOT EXISTS idx_ibe_item ON item_battle_effects(item_id);
CREATE INDEX IF NOT EXISTS idx_ibe_effect_type ON item_battle_effects(effect_type);
CREATE INDEX IF NOT EXISTS idx_mbe_move ON move_battle_effects(move_id);
CREATE INDEX IF NOT EXISTS idx_mbe_effect_type ON move_battle_effects(effect_type);

-- ==========================================================================
-- PART 1: ability_battle_effects
-- ==========================================================================

INSERT INTO ability_battle_effects
  (ability_id, effect_type, trigger, target, modifier_type, modifier_value, affected_stat, affected_type, affected_move_flag, affected_move_category, params, generation_start, generation_end, priority, note)
VALUES
  (2, 401, 2, 7, 4, 2, NULL, NULL, NULL, NULL, '{"turns":5}', 3, NULL, 0, 'Drizzle: rain 5t'),
  (70, 401, 2, 7, 4, 1, NULL, NULL, NULL, NULL, '{"turns":5}', 3, NULL, 0, 'Drought: sun 5t'),
  (45, 401, 2, 7, 4, 3, NULL, NULL, NULL, NULL, '{"turns":5}', 3, NULL, 0, 'Sand Stream: sand 5t'),
  (117, 401, 2, 7, 4, 4, NULL, NULL, NULL, NULL, '{"turns":5}', 4, NULL, 0, 'Snow Warning: snow 5t'),
  (189, 401, 2, 7, 4, 6, NULL, NULL, NULL, NULL, '{"permanent":true}', 6, NULL, 0, 'Primordial Sea: heavy rain'),
  (190, 401, 2, 7, 4, 5, NULL, NULL, NULL, NULL, '{"permanent":true}', 6, NULL, 0, 'Desolate Land: harsh sun'),
  (191, 401, 2, 7, 4, 7, NULL, NULL, NULL, NULL, '{"permanent":true}', 6, NULL, 0, 'Delta Stream: strong winds'),
  (226, 402, 2, 7, 5, 1, NULL, NULL, NULL, NULL, '{"turns":5}', 7, NULL, 0, 'Electric Surge'),
  (229, 402, 2, 7, 5, 2, NULL, NULL, NULL, NULL, '{"turns":5}', 7, NULL, 0, 'Grassy Surge'),
  (228, 402, 2, 7, 5, 3, NULL, NULL, NULL, NULL, '{"turns":5}', 7, NULL, 0, 'Misty Surge'),
  (227, 402, 2, 7, 5, 4, NULL, NULL, NULL, NULL, '{"turns":5}', 7, NULL, 0, 'Psychic Surge'),
  (288, 401, 2, 7, 4, 1, NULL, NULL, NULL, NULL, '{"turns":5}', 9, NULL, 0, 'Orichalcum Pulse: set sun'),
  (288, 101, 5, 1, 1, 1.3333, 2, NULL, NULL, NULL, '{"weather":1}', 9, NULL, 1, 'Orichalcum Pulse: sun Atk x1.3333'),
  (289, 402, 2, 7, 5, 1, NULL, NULL, NULL, NULL, '{"turns":5}', 9, NULL, 0, 'Hadron Engine: set elec terrain'),
  (289, 101, 6, 1, 1, 1.3333, 4, NULL, NULL, NULL, '{"terrain":1}', 9, NULL, 1, 'Hadron Engine: elec SpA x1.3333'),
  (26, 301, 1, 1, 3, NULL, NULL, 9, NULL, NULL, NULL, 3, NULL, 0, 'Levitate: immune Ground'),
  (25, 301, 1, 1, 6, NULL, NULL, NULL, NULL, NULL, '{"condition":"only_super_effective_hits"}', 3, NULL, 0, 'Wonder Guard: only SE hits'),
  (10, 302, 12, 1, 9, 0.25, NULL, 4, NULL, NULL, NULL, 3, NULL, 0, 'Volt Absorb: immune Electric heal 25%'),
  (11, 302, 12, 1, 9, 0.25, NULL, 3, NULL, NULL, NULL, 3, NULL, 0, 'Water Absorb: immune Water heal 25%'),
  (18, 302, 12, 1, 1, 1.5, NULL, 2, NULL, NULL, '{"boost_type":2}', 3, NULL, 0, 'Flash Fire: immune Fire boost x1.5'),
  (31, 302, 12, 1, 2, 1, 4, 4, NULL, NULL, NULL, 5, NULL, 0, 'Lightning Rod: immune Electric SpA+1'),
  (114, 302, 12, 1, 2, 1, 4, 3, NULL, NULL, NULL, 5, NULL, 0, 'Storm Drain: immune Water SpA+1'),
  (78, 302, 12, 1, 2, 1, 6, 4, NULL, NULL, NULL, 4, NULL, 0, 'Motor Drive: immune Electric Spe+1'),
  (157, 302, 12, 1, 2, 1, 2, 5, NULL, NULL, NULL, 5, NULL, 0, 'Sap Sipper: immune Grass Atk+1'),
  (297, 302, 12, 1, 9, 0.25, NULL, 9, NULL, NULL, NULL, 9, NULL, 0, 'Earth Eater: immune Ground heal 25%'),
  (273, 302, 12, 1, 2, 2, 3, 2, NULL, NULL, NULL, 9, NULL, 0, 'Well-Baked Body: immune Fire Def+2'),
  (274, 302, 12, 1, 2, 1, 2, NULL, 8, NULL, NULL, 9, NULL, 0, 'Wind Rider: immune Wind Atk+1'),
  (87, 302, 12, 1, 9, 0.25, NULL, 3, NULL, NULL, NULL, 4, NULL, 0, 'Dry Skin: immune Water heal 25%'),
  (87, 202, 12, 1, 1, 1.25, NULL, 2, NULL, NULL, NULL, 4, NULL, 1, 'Dry Skin: Fire damage x1.25'),
  (37, 101, 1, 1, 1, 2.0, 2, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Huge Power: Atk x2'),
  (74, 101, 1, 1, 1, 2.0, 2, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Pure Power: Atk x2'),
  (255, 101, 1, 1, 1, 1.5, 2, NULL, NULL, NULL, '{"lock_move":true}', 8, NULL, 0, 'Gorilla Tactics: Atk x1.5 lock'),
  (169, 101, 1, 1, 1, 2.0, 3, NULL, NULL, NULL, NULL, 6, NULL, 0, 'Fur Coat: Def x2'),
  (55, 101, 7, 1, 1, 1.5, 2, NULL, NULL, 1, '{"accuracy_penalty":0.8}', 3, NULL, 0, 'Hustle: phys Atk x1.5'),
  (62, 101, 11, 1, 1, 1.5, 2, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Guts: status Atk x1.5'),
  (63, 101, 11, 1, 1, 1.5, 3, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Marvel Scale: status Def x1.5'),
  (95, 101, 11, 1, 1, 1.5, 6, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Quick Feet: status Spe x1.5'),
  (33, 101, 5, 1, 1, 2.0, 6, NULL, NULL, NULL, '{"weather":2}', 3, NULL, 0, 'Swift Swim: rain Spe x2'),
  (34, 101, 5, 1, 1, 2.0, 6, NULL, NULL, NULL, '{"weather":1}', 3, NULL, 0, 'Chlorophyll: sun Spe x2'),
  (146, 101, 5, 1, 1, 2.0, 6, NULL, NULL, NULL, '{"weather":3}', 5, NULL, 0, 'Sand Rush: sand Spe x2'),
  (202, 101, 5, 1, 1, 2.0, 6, NULL, NULL, NULL, '{"weather":4}', 7, NULL, 0, 'Slush Rush: snow Spe x2'),
  (207, 101, 6, 1, 1, 2.0, 6, NULL, NULL, NULL, '{"terrain":1}', 7, NULL, 0, 'Surge Surfer: elec Spe x2'),
  (84, 101, 1, 1, 1, 2.0, 6, NULL, NULL, NULL, '{"condition":"item_consumed"}', 4, NULL, 0, 'Unburden: Spe x2 after item'),
  (94, 101, 5, 1, 1, 1.5, 4, NULL, NULL, NULL, '{"weather":1,"hp_cost":0.125}', 4, NULL, 0, 'Solar Power: sun SpA x1.5'),
  (112, 101, 2, 1, 1, 0.5, 2, NULL, NULL, NULL, '{"duration":5}', 4, NULL, 0, 'Slow Start: 5t Atk x0.5'),
  (112, 101, 2, 1, 1, 0.5, 6, NULL, NULL, NULL, '{"duration":5}', 4, NULL, 1, 'Slow Start: 5t Spe x0.5'),
  (129, 101, 3, 1, 1, 0.5, 2, NULL, NULL, NULL, '{"threshold":0.5}', 5, NULL, 0, 'Defeatist: HP<=50% Atk x0.5'),
  (129, 101, 3, 1, 1, 0.5, 4, NULL, NULL, NULL, '{"threshold":0.5}', 5, NULL, 1, 'Defeatist: HP<=50% SpA x0.5'),
  (181, 201, 7, 1, 1, 1.3, NULL, NULL, 1, NULL, NULL, 6, NULL, 0, 'Tough Claws: contact x1.3'),
  (89, 201, 7, 1, 1, 1.2, NULL, NULL, 3, NULL, NULL, 4, NULL, 0, 'Iron Fist: punch x1.2'),
  (178, 201, 7, 1, 1, 1.5, NULL, NULL, 5, NULL, NULL, 6, NULL, 0, 'Mega Launcher: pulse x1.5'),
  (173, 201, 7, 1, 1, 1.5, NULL, NULL, 4, NULL, NULL, 6, NULL, 0, 'Strong Jaw: bite x1.5'),
  (120, 201, 7, 1, 1, 1.2, NULL, NULL, 10, NULL, NULL, 4, NULL, 0, 'Reckless: recoil x1.2'),
  (292, 201, 7, 1, 1, 1.5, NULL, NULL, 9, NULL, NULL, 9, NULL, 0, 'Sharpness: slicing x1.5'),
  (244, 201, 7, 1, 1, 1.3, NULL, NULL, 2, NULL, NULL, 8, NULL, 0, 'Punk Rock: sound x1.3 offensive'),
  (244, 202, 8, 1, 1, 0.5, NULL, NULL, 2, NULL, NULL, 8, NULL, 1, 'Punk Rock: sound x0.5 defensive'),
  (276, 201, 13, 1, 1, 1.5, NULL, 13, NULL, NULL, NULL, 9, NULL, 0, 'Rocky Payload: Rock x1.5'),
  (200, 201, 13, 1, 1, 1.5, NULL, 17, NULL, NULL, NULL, 7, NULL, 0, 'Steelworker: Steel x1.5'),
  (263, 201, 13, 1, 1, 1.5, NULL, 15, NULL, NULL, NULL, 8, NULL, 0, 'Dragons Maw: Dragon x1.5'),
  (262, 201, 13, 1, 1, 1.5, NULL, 4, NULL, NULL, NULL, 8, 8, 0, 'Transistor: Electric x1.5 Gen8'),
  (262, 201, 13, 1, 1, 1.3, NULL, 4, NULL, NULL, NULL, 9, NULL, 0, 'Transistor: Electric x1.3 Gen9+'),
  (101, 201, 15, 1, 1, 1.5, NULL, NULL, NULL, NULL, '{"max_bp":60}', 4, NULL, 0, 'Technician: bp<=60 x1.5'),
  (148, 201, 16, 1, 1, 1.3, NULL, NULL, NULL, NULL, NULL, 5, NULL, 0, 'Analytic: last x1.3'),
  (198, 201, 7, 1, 1, 2.0, NULL, NULL, NULL, NULL, '{"condition":"target_switched_in"}', 7, NULL, 0, 'Stakeout: vs switch x2'),
  (125, 201, 7, 1, 1, 1.3, NULL, NULL, NULL, NULL, '{"condition":"has_secondary_effect"}', 5, NULL, 0, 'Sheer Force: secondary x1.3'),
  (137, 201, 11, 1, 1, 1.5, NULL, NULL, NULL, 1, '{"status":"poison"}', 5, NULL, 0, 'Toxic Boost: poison phys x1.5'),
  (138, 201, 11, 1, 1, 1.5, NULL, NULL, NULL, 2, '{"status":"burn"}', 5, NULL, 0, 'Flare Boost: burn spec x1.5'),
  (65, 201, 3, 1, 1, 1.5, NULL, 5, NULL, NULL, '{"hp_threshold":0.333}', 3, NULL, 0, 'Overgrow: HP<=1/3 Grass x1.5'),
  (66, 201, 3, 1, 1, 1.5, NULL, 2, NULL, NULL, '{"hp_threshold":0.333}', 3, NULL, 0, 'Blaze: HP<=1/3 Fire x1.5'),
  (67, 201, 3, 1, 1, 1.5, NULL, 3, NULL, NULL, '{"hp_threshold":0.333}', 3, NULL, 0, 'Torrent: HP<=1/3 Water x1.5'),
  (68, 201, 3, 1, 1, 1.5, NULL, 12, NULL, NULL, '{"hp_threshold":0.333}', 3, NULL, 0, 'Swarm: HP<=1/3 Bug x1.5'),
  (159, 205, 5, 1, 1, 1.3, NULL, NULL, NULL, NULL, '{"weather":3,"boosted_types":[13,9,17]}', 5, NULL, 0, 'Sand Force: sand Rock/Ground/Steel x1.3'),
  (199, 201, 13, 1, 1, 2.0, NULL, 3, NULL, NULL, NULL, 7, NULL, 0, 'Water Bubble: Water x2'),
  (199, 202, 8, 1, 1, 0.5, NULL, 2, NULL, NULL, NULL, 7, NULL, 1, 'Water Bubble: Fire received x0.5'),
  (47, 202, 8, 1, 1, 0.5, NULL, 2, NULL, NULL, NULL, 3, NULL, 0, 'Thick Fat: Fire x0.5'),
  (47, 202, 8, 1, 1, 0.5, NULL, 6, NULL, NULL, NULL, 3, NULL, 1, 'Thick Fat: Ice x0.5'),
  (85, 202, 8, 1, 1, 0.5, NULL, 2, NULL, NULL, NULL, 4, NULL, 0, 'Heatproof: Fire x0.5'),
  (272, 202, 8, 1, 1, 0.5, NULL, 14, NULL, NULL, NULL, 9, NULL, 0, 'Purifying Salt: Ghost x0.5'),
  (246, 202, 8, 1, 1, 0.5, NULL, NULL, NULL, 2, NULL, 8, NULL, 0, 'Ice Scales: special x0.5'),
  (136, 202, 4, 1, 1, 0.5, NULL, NULL, NULL, NULL, NULL, 5, NULL, 0, 'Multiscale: full HP x0.5'),
  (231, 202, 4, 1, 1, 0.5, NULL, NULL, NULL, NULL, NULL, 7, NULL, 0, 'Shadow Shield: full HP x0.5'),
  (218, 202, 9, 1, 1, 0.5, NULL, NULL, 1, NULL, NULL, 7, NULL, 0, 'Fluffy: contact x0.5'),
  (218, 202, 12, 1, 1, 2.0, NULL, 2, NULL, NULL, NULL, 7, NULL, 1, 'Fluffy: Fire x2'),
  (111, 203, 10, 1, 1, 0.75, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Filter: SE x0.75'),
  (116, 203, 10, 1, 1, 0.75, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Solid Rock: SE x0.75'),
  (232, 203, 10, 1, 1, 0.75, NULL, NULL, NULL, NULL, NULL, 7, NULL, 0, 'Prism Armor: SE x0.75'),
  (233, 203, 7, 1, 1, 1.25, NULL, NULL, NULL, NULL, NULL, 7, NULL, 0, 'Neuroforce: SE x1.25'),
  (110, 204, 7, 1, 1, 2.0, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Tinted Lens: NVE x2'),
  (91, 305, 1, 1, 1, 2.0, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Adaptability: STAB=2.0'),
  (182, 303, 13, 1, 1, 1.2, NULL, 18, NULL, NULL, '{"from_type":1,"to_type":18}', 6, NULL, 0, 'Pixilate: Normal->Fairy x1.2'),
  (184, 303, 13, 1, 1, 1.2, NULL, 10, NULL, NULL, '{"from_type":1,"to_type":10}', 6, NULL, 0, 'Aerilate: Normal->Flying x1.2'),
  (174, 303, 13, 1, 1, 1.2, NULL, 6, NULL, NULL, '{"from_type":1,"to_type":6}', 6, NULL, 0, 'Refrigerate: Normal->Ice x1.2'),
  (206, 303, 13, 1, 1, 1.2, NULL, 4, NULL, NULL, '{"from_type":1,"to_type":4}', 7, NULL, 0, 'Galvanize: Normal->Electric x1.2'),
  (312, 303, 13, 1, 1, 1.2, NULL, 15, NULL, NULL, '{"from_type":1,"to_type":15}', 9, NULL, 0, 'Draconize: Normal->Dragon x1.2'),
  (96, 303, 1, 1, 1, 1.0, NULL, 1, NULL, NULL, '{"from_type":"all","to_type":1}', 4, 6, 0, 'Normalize: all->Normal Gen4-6'),
  (96, 303, 1, 1, 1, 1.2, NULL, 1, NULL, NULL, '{"from_type":"all","to_type":1}', 7, NULL, 0, 'Normalize: all->Normal x1.2 Gen7+'),
  (204, 303, 7, 1, 1, 1.0, NULL, 3, 2, NULL, '{"to_type":3}', 7, NULL, 0, 'Liquid Voice: sound->Water'),
  (186, 201, 1, 7, 1, 1.33, NULL, 16, NULL, NULL, NULL, 6, NULL, 0, 'Dark Aura: field Dark x1.33'),
  (187, 201, 1, 7, 1, 1.33, NULL, 18, NULL, NULL, NULL, 6, NULL, 0, 'Fairy Aura: field Fairy x1.33'),
  (188, 201, 1, 7, 1, 0.75, NULL, NULL, NULL, NULL, '{"condition":"reverses_aura"}', 6, NULL, 0, 'Aura Break: x0.75'),
  (284, 101, 1, 3, 1, 0.75, 4, NULL, NULL, NULL, NULL, 9, NULL, 0, 'Vessel of Ruin: foe SpA x0.75'),
  (285, 101, 1, 3, 1, 0.75, 3, NULL, NULL, NULL, NULL, 9, NULL, 0, 'Sword of Ruin: foe Def x0.75'),
  (286, 101, 1, 3, 1, 0.75, 2, NULL, NULL, NULL, NULL, 9, NULL, 0, 'Tablets of Ruin: foe Atk x0.75'),
  (287, 101, 1, 3, 1, 0.75, 5, NULL, NULL, NULL, NULL, 9, NULL, 0, 'Beads of Ruin: foe SpD x0.75'),
  (22, 102, 2, 3, 2, -1, 2, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Intimidate: foe Atk -1'),
  (88, 102, 2, 1, 2, 1, NULL, NULL, NULL, NULL, '{"condition":"compare_def_spd"}', 4, NULL, 0, 'Download: +1 Atk or SpA'),
  (234, 102, 2, 1, 2, 1, 2, NULL, NULL, NULL, NULL, 8, NULL, 0, 'Intrepid Sword: Atk +1'),
  (235, 102, 2, 1, 2, 1, 3, NULL, NULL, NULL, NULL, 8, NULL, 0, 'Dauntless Shield: Def +1'),
  (306, 102, 2, 3, 2, -1, 8, NULL, NULL, NULL, NULL, 9, NULL, 0, 'Supersweet Syrup: foe Evasion -1'),
  (97, 502, 1, 1, 1, 1.5, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Sniper: crit x1.5 extra'),
  (105, 501, 1, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Super Luck: crit +1'),
  (4, 503, 1, 1, 6, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Battle Armor: no crit'),
  (75, 503, 1, 1, 6, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Shell Armor: no crit'),
  (252, 201, 1, 5, 1, 1.5, NULL, 17, NULL, NULL, NULL, 8, NULL, 0, 'Steely Spirit: team Steel x1.5'),
  (249, 201, 1, 4, 1, 1.3, NULL, NULL, NULL, NULL, NULL, 8, NULL, 0, 'Power Spot: ally x1.3'),
  (217, 201, 1, 4, 1, 1.3, NULL, NULL, NULL, 2, NULL, 7, NULL, 0, 'Battery: ally special x1.3'),
  (132, 202, 1, 4, 1, 0.75, NULL, NULL, NULL, NULL, NULL, 5, NULL, 0, 'Friend Guard: ally dmg x0.75'),
  (162, 101, 1, 5, 1, 1.1, 7, NULL, NULL, NULL, NULL, 5, NULL, 0, 'Victory Star: team acc x1.1'),
  (185, 901, 7, 2, 8, 2, NULL, NULL, NULL, NULL, '{"second_hit_multiplier":0.25}', 7, NULL, 0, 'Parental Bond: 2 hits 2nd x0.25'),
  (293, 201, 17, 1, 1, 1.1, NULL, NULL, NULL, NULL, '{"per_fainted_ally":0.1,"max":1.5}', 9, NULL, 0, 'Supreme Overlord: +10% per fainted'),
  (153, 201, 7, 1, 1, 1.25, NULL, NULL, NULL, NULL, '{"condition":"same_gender"}', 4, NULL, 0, 'Rivalry: same gender x1.25'),
  (153, 201, 7, 1, 1, 0.75, NULL, NULL, NULL, NULL, '{"condition":"opposite_gender"}', 4, NULL, 1, 'Rivalry: opp gender x0.75'),
  (104, 1002, 7, 2, 6, NULL, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Mold Breaker: ignore ability'),
  (163, 1002, 7, 2, 6, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, 0, 'Turboblaze: ignore ability'),
  (164, 1002, 7, 2, 6, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, 0, 'Teravolt: ignore ability');

-- ==========================================================================
-- PART 2: item_battle_effects
-- ==========================================================================

INSERT INTO item_battle_effects
  (item_id, effect_type, trigger, target, modifier_type, modifier_value, affected_stat, affected_type, affected_move_flag, affected_move_category, params, consumable, species_restriction, generation_start, generation_end, priority, note)
VALUES
  (54, 101, 1, 1, 1, 1.5, 2, NULL, NULL, NULL, '{"lock_move":true}', 0, NULL, 3, NULL, 0, 'Choice Band: Atk x1.5'),
  (55, 101, 1, 1, 1, 1.5, 4, NULL, NULL, NULL, '{"lock_move":true}', 0, NULL, 4, NULL, 0, 'Choice Specs: SpA x1.5'),
  (56, 101, 1, 1, 1, 1.5, 6, NULL, NULL, NULL, '{"lock_move":true}', 0, NULL, 4, NULL, 0, 'Choice Scarf: Spe x1.5'),
  (106, 201, 7, 1, 1, 1.1, NULL, NULL, NULL, 1, NULL, 0, NULL, 4, NULL, 0, 'Muscle Band: phys x1.1'),
  (107, 201, 7, 1, 1, 1.1, NULL, NULL, NULL, 2, NULL, 0, NULL, 4, NULL, 0, 'Wise Glasses: spec x1.1'),
  (169, 101, 1, 1, 1, 1.5, 5, NULL, NULL, NULL, '{"block_category":3}', 0, NULL, 6, NULL, 0, 'Assault Vest: SpD x1.5'),
  (139, 101, 1, 1, 1, 1.5, 3, NULL, NULL, NULL, '{"condition":"not_fully_evolved"}', 0, NULL, 5, NULL, 0, 'Eviolite: Def x1.5 NFE'),
  (139, 101, 1, 1, 1, 1.5, 5, NULL, NULL, NULL, '{"condition":"not_fully_evolved"}', 0, NULL, 5, NULL, 1, 'Eviolite: SpD x1.5 NFE'),
  (110, 201, 7, 1, 1, 1.3, NULL, NULL, NULL, NULL, '{"recoil_fraction":0.1}', 0, NULL, 4, NULL, 0, 'Life Orb: x1.3 -10%'),
  (108, 203, 7, 1, 1, 1.2, NULL, NULL, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Expert Belt: SE x1.2'),
  (220, 201, 7, 1, 1, 1.1, NULL, NULL, 3, NULL, '{"removes_contact":true}', 0, NULL, 9, NULL, 0, 'Punching Glove: punch x1.1'),
  (31, 201, 13, 1, 1, 1.2, NULL, 1, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Silk Scarf: Normal x1.2'),
  (28, 201, 13, 1, 1, 1.2, NULL, 2, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Charcoal: Fire x1.2'),
  (22, 201, 13, 1, 1, 1.2, NULL, 3, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Mystic Water: Water x1.2'),
  (21, 201, 13, 1, 1, 1.2, NULL, 4, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Magnet: Electric x1.2'),
  (18, 201, 13, 1, 1, 1.2, NULL, 5, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Miracle Seed: Grass x1.2'),
  (25, 201, 13, 1, 1, 1.2, NULL, 6, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Never-Melt Ice: Ice x1.2'),
  (20, 201, 13, 1, 1, 1.2, NULL, 7, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Black Belt: Fighting x1.2'),
  (24, 201, 13, 1, 1, 1.2, NULL, 8, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Poison Barb: Poison x1.2'),
  (16, 201, 13, 1, 1, 1.2, NULL, 9, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Soft Sand: Ground x1.2'),
  (23, 201, 13, 1, 1, 1.2, NULL, 10, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Sharp Beak: Flying x1.2'),
  (27, 201, 13, 1, 1, 1.2, NULL, 11, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Twisted Spoon: Psychic x1.2'),
  (4, 201, 13, 1, 1, 1.2, NULL, 12, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Silver Powder: Bug x1.2'),
  (17, 201, 13, 1, 1, 1.2, NULL, 13, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Hard Stone: Rock x1.2'),
  (26, 201, 13, 1, 1, 1.2, NULL, 14, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Spell Tag: Ghost x1.2'),
  (29, 201, 13, 1, 1, 1.2, NULL, 15, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Dragon Fang: Dragon x1.2'),
  (19, 201, 13, 1, 1, 1.2, NULL, 16, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Black Glasses: Dark x1.2'),
  (12, 201, 13, 1, 1, 1.2, NULL, 17, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Metal Coat: Steel x1.2'),
  (77, 201, 13, 1, 1, 1.2, NULL, 2, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Flame Plate: Fire x1.2'),
  (78, 201, 13, 1, 1, 1.2, NULL, 3, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Splash Plate: Water x1.2'),
  (79, 201, 13, 1, 1, 1.2, NULL, 4, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Zap Plate: Electric x1.2'),
  (80, 201, 13, 1, 1, 1.2, NULL, 5, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Meadow Plate: Grass x1.2'),
  (81, 201, 13, 1, 1, 1.2, NULL, 6, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Icicle Plate: Ice x1.2'),
  (82, 201, 13, 1, 1, 1.2, NULL, 7, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Fist Plate: Fighting x1.2'),
  (83, 201, 13, 1, 1, 1.2, NULL, 8, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Toxic Plate: Poison x1.2'),
  (84, 201, 13, 1, 1, 1.2, NULL, 9, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Earth Plate: Ground x1.2'),
  (85, 201, 13, 1, 1, 1.2, NULL, 10, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Sky Plate: Flying x1.2'),
  (86, 201, 13, 1, 1, 1.2, NULL, 11, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Mind Plate: Psychic x1.2'),
  (87, 201, 13, 1, 1, 1.2, NULL, 12, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Insect Plate: Bug x1.2'),
  (88, 201, 13, 1, 1, 1.2, NULL, 13, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Stone Plate: Rock x1.2'),
  (89, 201, 13, 1, 1, 1.2, NULL, 14, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Spooky Plate: Ghost x1.2'),
  (90, 201, 13, 1, 1, 1.2, NULL, 15, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Draco Plate: Dragon x1.2'),
  (91, 201, 13, 1, 1, 1.2, NULL, 16, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Dread Plate: Dark x1.2'),
  (92, 201, 13, 1, 1, 1.2, NULL, 17, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Iron Plate: Steel x1.2'),
  (93, 201, 13, 1, 1, 1.2, NULL, 18, NULL, NULL, NULL, 0, NULL, 6, NULL, 0, 'Pixie Plate: Fairy x1.2'),
  (37, 101, 1, 1, 1, 2.0, 2, NULL, NULL, NULL, NULL, 0, '[104,105]', 1, NULL, 0, 'Thick Club: Cubone/Marowak Atk x2'),
  (15, 101, 1, 1, 1, 2.0, 2, NULL, NULL, NULL, NULL, 0, '[25]', 4, NULL, 0, 'Light Ball: Pikachu Atk x2'),
  (15, 101, 1, 1, 1, 2.0, 4, NULL, NULL, NULL, NULL, 0, '[25]', 4, NULL, 1, 'Light Ball: Pikachu SpA x2'),
  (38, 501, 1, 1, 2, 2, NULL, NULL, NULL, NULL, NULL, 0, '[83,865]', 2, NULL, 0, 'Leek: Farfetchd crit+2'),
  (34, 501, 1, 1, 2, 2, NULL, NULL, NULL, NULL, NULL, 0, '[113]', 2, NULL, 0, 'Lucky Punch: Chansey crit+2'),
  (35, 101, 1, 1, 1, 2.0, 3, NULL, NULL, NULL, '{"condition":"not_transformed"}', 0, '[132]', 2, NULL, 0, 'Metal Powder: Ditto Def x2'),
  (36, 101, 1, 1, 1, 2.0, 6, NULL, NULL, NULL, '{"condition":"not_transformed"}', 0, '[132]', 4, NULL, 0, 'Quick Powder: Ditto Spe x2'),
  (59, 101, 1, 1, 1, 2.0, 5, NULL, NULL, NULL, NULL, 0, '[366]', 3, NULL, 0, 'Deep Sea Scale: Clamperl SpD x2'),
  (58, 101, 1, 1, 1, 2.0, 4, NULL, NULL, NULL, NULL, 0, '[366]', 3, NULL, 0, 'Deep Sea Tooth: Clamperl SpA x2'),
  (165, 201, 13, 1, 1, 1.3, NULL, 1, NULL, NULL, NULL, 1, NULL, 5, NULL, 0, 'Normal Gem: Normal x1.3'),
  (149, 201, 13, 1, 1, 1.3, NULL, 2, NULL, NULL, NULL, 1, NULL, 5, NULL, 0, 'Fire Gem: Fire x1.3'),
  (150, 201, 13, 1, 1, 1.3, NULL, 3, NULL, NULL, NULL, 1, NULL, 5, NULL, 0, 'Water Gem: Water x1.3'),
  (151, 201, 13, 1, 1, 1.3, NULL, 4, NULL, NULL, NULL, 1, NULL, 5, NULL, 0, 'Electric Gem: Electric x1.3'),
  (369, 1003, 10, 1, 1, 0.5, NULL, 2, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Occa Berry: SE Fire x0.5'),
  (365, 1003, 10, 1, 1, 0.5, NULL, 3, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Passho Berry: SE Water x0.5'),
  (399, 1003, 10, 1, 1, 0.5, NULL, 4, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Wacan Berry: SE Electric x0.5'),
  (397, 1003, 10, 1, 1, 0.5, NULL, 6, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Yache Berry: SE Ice x0.5'),
  (413, 1003, 10, 1, 1, 0.5, NULL, 7, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Chople Berry: SE Fighting x0.5'),
  (401, 1003, 10, 1, 1, 0.5, NULL, 8, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Kebia Berry: SE Poison x0.5'),
  (403, 1003, 10, 1, 1, 0.5, NULL, 9, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Shuca Berry: SE Ground x0.5'),
  (404, 1003, 10, 1, 1, 0.5, NULL, 10, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Coba Berry: SE Flying x0.5'),
  (405, 1003, 10, 1, 1, 0.5, NULL, 11, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Payapa Berry: SE Psychic x0.5'),
  (410, 1003, 10, 1, 1, 0.5, NULL, 12, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Tanga Berry: SE Bug x0.5'),
  (415, 1003, 10, 1, 1, 0.5, NULL, 13, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Charti Berry: SE Rock x0.5'),
  (411, 1003, 10, 1, 1, 0.5, NULL, 14, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Kasib Berry: SE Ghost x0.5'),
  (407, 1003, 10, 1, 1, 0.5, NULL, 17, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Babiri Berry: SE Steel x0.5'),
  (386, 1003, 8, 1, 1, 0.5, NULL, 1, NULL, NULL, NULL, 1, NULL, 3, NULL, 0, 'Chilan Berry: Normal x0.5'),
  (113, 703, 4, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 1, NULL, 4, NULL, 0, 'Focus Sash: survive 1HP'),
  (167, 102, 10, 1, 2, 2, 2, NULL, NULL, NULL, NULL, 1, NULL, 6, NULL, 0, 'Weakness Policy: SE Atk+2'),
  (167, 102, 10, 1, 2, 2, 4, NULL, NULL, NULL, NULL, 1, NULL, 6, NULL, 1, 'Weakness Policy: SE SpA+2'),
  (178, 102, 6, 1, 2, 1, 3, NULL, NULL, NULL, '{"terrain":1}', 1, NULL, 7, NULL, 0, 'Electric Seed: elec Def+1'),
  (181, 102, 6, 1, 2, 1, 3, NULL, NULL, NULL, '{"terrain":2}', 1, NULL, 7, NULL, 0, 'Grassy Seed: grass Def+1'),
  (180, 102, 6, 1, 2, 1, 5, NULL, NULL, NULL, '{"terrain":3}', 1, NULL, 7, NULL, 0, 'Misty Seed: misty SpD+1'),
  (179, 102, 6, 1, 2, 1, 5, NULL, NULL, NULL, '{"terrain":4}', 1, NULL, 7, NULL, 0, 'Psychic Seed: psychic SpD+1'),
  (216, 101, 1, 1, 1, 1.3, NULL, NULL, NULL, NULL, '{"condition":"protosynthesis_or_quark_drive","boost_highest_stat":true}', 1, NULL, 9, NULL, 0, 'Booster Energy: highest x1.3'),
  (103, 501, 1, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, 0, NULL, 4, NULL, 0, 'Razor Claw: crit+1'),
  (11, 501, 1, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, 0, NULL, 2, NULL, 0, 'Scope Lens: crit+1');

-- ==========================================================================
-- PART 3: move_flags
-- ==========================================================================

-- contact (1)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (370, 1),
  (418, 1),
  (453, 1),
  (7, 1),
  (9, 1),
  (8, 1),
  (200, 1),
  (242, 1),
  (421, 1),
  (344, 1),
  (442, 1),
  (583, 1),
  (98, 1),
  (36, 1),
  (413, 1),
  (394, 1),
  (452, 1),
  (457, 1),
  (183, 1),
  (245, 1),
  (44, 1),
  (422, 1),
  (423, 1),
  (424, 1),
  (400, 1),
  (404, 1),
  (348, 1),
  (409, 1),
  (309, 1),
  (325, 1),
  (276, 1),
  (904, 1),
  (651, 1),
  (533, 1),
  (210, 1),
  (89, 1),
  (24, 1),
  (167, 1),
  (4, 1);

-- sound (2)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (49, 2),
  (405, 2),
  (496, 2),
  (46, 2),
  (768, 2),
  (886, 2);

-- punch (3)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (418, 3),
  (7, 3),
  (9, 3),
  (8, 3),
  (183, 3),
  (309, 3),
  (325, 3),
  (409, 3),
  (904, 3),
  (703, 3);

-- bite (4)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (44, 4),
  (242, 4),
  (305, 4),
  (422, 4),
  (423, 4),
  (424, 4);

-- pulse (5)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (352, 5),
  (396, 5),
  (406, 5),
  (399, 5),
  (505, 5),
  (813, 5);

-- ball (6)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (247, 6),
  (412, 6),
  (486, 6),
  (360, 6),
  (188, 6),
  (439, 6);

-- powder (7)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (77, 7),
  (78, 7),
  (79, 7),
  (147, 7);

-- wind (8)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (16, 8),
  (18, 8),
  (196, 8),
  (239, 8),
  (257, 8),
  (366, 8),
  (542, 8);

-- slicing (9)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (15, 9),
  (75, 9),
  (404, 9),
  (210, 9),
  (348, 9),
  (400, 9),
  (427, 9),
  (533, 9),
  (548, 9),
  (651, 9);

-- recoil (10)
INSERT OR IGNORE INTO move_flags (move_id, flag) VALUES
  (36, 10),
  (457, 10),
  (394, 10),
  (452, 10),
  (344, 10),
  (413, 10),
  (276, 10),
  (907, 10);

-- ==========================================================================
-- PART 4: move_battle_effects
-- ==========================================================================

INSERT INTO move_battle_effects
  (move_id, effect_type, trigger, target, modifier_type, modifier_value, affected_stat, affected_type, affected_move_flag, affected_move_category, params, generation_start, generation_end, priority, note)
VALUES
  (370, 102, 7, 1, 2, -1, 3, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Close Combat: self Def-1'),
  (370, 102, 7, 1, 2, -1, 5, NULL, NULL, NULL, NULL, 4, NULL, 1, 'Close Combat: self SpD-1'),
  (434, 102, 7, 1, 2, -2, 4, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Draco Meteor: self SpA-2'),
  (315, 102, 7, 1, 2, -2, 4, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Overheat: self SpA-2'),
  (276, 102, 7, 1, 2, -1, 2, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Superpower: self Atk-1'),
  (276, 102, 7, 1, 2, -1, 3, NULL, NULL, NULL, NULL, 3, NULL, 1, 'Superpower: self Def-1'),
  (418, 601, 1, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Bullet Punch: +1'),
  (453, 601, 1, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Aqua Jet: +1'),
  (183, 601, 1, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 2, NULL, 0, 'Mach Punch: +1'),
  (98, 601, 1, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 1, NULL, 0, 'Quick Attack: +1'),
  (245, 601, 1, 1, 8, 2, NULL, NULL, NULL, NULL, NULL, 2, NULL, 0, 'Extreme Speed: +2'),
  (333, 601, 1, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Ice Shard: +1'),
  (400, 504, 1, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Storm Throw: always crit'),
  (651, 504, 1, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 7, NULL, 0, 'Solar Blade: charge crit'),
  (658, 504, 1, 1, 8, 1, NULL, NULL, NULL, NULL, NULL, 6, NULL, 0, 'Pollen Puff: always crit'),
  (404, 501, 1, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, 1, NULL, 0, 'Cross Poison: crit+1'),
  (348, 501, 1, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Leaf Blade: crit+1'),
  (427, 501, 1, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Psycho Cut: crit+1'),
  (163, 501, 1, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, 1, NULL, 0, 'Slash: crit+1'),
  (394, 802, 7, 1, 9, 0.333, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Flare Blitz: 1/3 recoil'),
  (452, 802, 7, 1, 9, 0.333, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Wood Hammer: 1/3 recoil'),
  (344, 802, 7, 1, 9, 0.333, NULL, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Volt Tackle: 1/3 recoil'),
  (413, 802, 7, 1, 9, 0.333, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Brave Bird: 1/3 recoil'),
  (457, 802, 7, 1, 9, 0.5, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Head Smash: 1/2 recoil'),
  (36, 802, 7, 1, 9, 0.25, NULL, NULL, NULL, NULL, NULL, 1, NULL, 0, 'Take Down: 1/4 recoil'),
  (71, 803, 7, 1, 9, 0.5, NULL, NULL, NULL, NULL, NULL, 1, NULL, 0, 'Absorb: heal 50%'),
  (72, 803, 7, 1, 9, 0.5, NULL, NULL, NULL, NULL, NULL, 1, NULL, 0, 'Mega Drain: heal 50%'),
  (202, 803, 7, 1, 9, 0.5, NULL, NULL, NULL, NULL, NULL, 3, NULL, 0, 'Giga Drain: heal 50%'),
  (409, 803, 7, 1, 9, 0.5, NULL, NULL, NULL, NULL, NULL, 4, NULL, 0, 'Drain Punch: heal 50%'),
  (69, 902, 1, 2, 8, NULL, NULL, NULL, NULL, NULL, '{"formula":"level_based"}', 1, NULL, 0, 'Seismic Toss: dmg=level'),
  (101, 902, 1, 2, 8, NULL, NULL, NULL, NULL, NULL, '{"formula":"level_based"}', 1, NULL, 0, 'Night Shade: dmg=level'),
  (447, 902, 1, 2, 8, NULL, NULL, NULL, NULL, NULL, '{"formula":"weight_based"}', 4, NULL, 0, 'Grass Knot: by weight'),
  (67, 902, 1, 2, 8, NULL, NULL, NULL, NULL, NULL, '{"formula":"weight_based"}', 3, NULL, 0, 'Low Kick: by weight'),
  (360, 902, 1, 2, 8, NULL, NULL, NULL, NULL, NULL, '{"formula":"speed_inverse"}', 4, NULL, 0, 'Gyro Ball: by speed diff'),
  (486, 902, 1, 2, 8, NULL, NULL, NULL, NULL, NULL, '{"formula":"speed_ratio"}', 4, NULL, 0, 'Electro Ball: by speed ratio'),
  (167, 901, 1, 2, 8, 3, NULL, NULL, NULL, NULL, '{"hits":3,"fixed":true}', 3, NULL, 0, 'Triple Kick: 3 hits'),
  (4, 901, 1, 2, 8, 5, NULL, NULL, NULL, NULL, '{"hits":[2,5]}', 1, NULL, 0, 'Comet Punch: 2-5 hits'),
  (24, 901, 1, 2, 8, 2, NULL, NULL, NULL, NULL, '{"hits":2,"fixed":true}', 1, NULL, 0, 'Double Kick: 2 hits');

-- DONE
